[package]
name = "rusty-volleyball-game"
version = "0.1.6"
edition = "2021"
authors = ["Anaxímeno Brito"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7"
structopt = "0.3"